const sampleData= [{"id":485828,
                   "vehicleId":45,
                 "totalFuel":21,
              "hyoungNo":"TP113","vehicleType":"TP",
              "vehicleModel":"ZZ3257N3247B",
              "vehicleManufacturer":"SINOTRUK HOWO",
              "expectedAveraged":43,
              "defaultEmployees":28487,
              "siteId":1,
              "excessWorkingHrCost":null,
              "date":"2023-05-09T08:00:55",
              "maxSpeed":13.10,
              "avgSpeed":4.70,
              "totalDistance":44407,
              "fuelLost":0,
              "isAverageKm":true,
              "flowMeterFuelUsed":null,
              "flowMeterFuelLost":0,
              "flowMeterEffiency":0,
              "fuelEfficiency":0.00,"engHours":null,
              "flowMeterEngineHrs":null,
              "isNightShift":false,"comments":"Demo data","isModified":false},
              {"id":485876,"vehicleId":52,"totalFuel":15,"hyoungNo":"TP119","vehicleType":"TP",
              "vehicleModel":"ZZ3257N3247B","vehicleManufacturer":"SINOTRUK HOWO","expectedAveraged":0,"defaultEmployees":28489,
              "siteId":18,"excessWorkingHrCost":null,"date":"2023-05-09T00:00:03","maxSpeed":9.70,"avgSpeed":1.80,"totalDistance":26787,
              "fuelLost":0,"isAverageKm":true,"flowMeterFuelUsed":null,"flowMeterFuelLost":0,"flowMeterEffiency":0,"fuelEfficiency":0.00,"engHours":null,
              "flowMeterEngineHrs":null,"isNightShift":false,"comments":"Demo data","isModified":false}]


export default sampleData;

