//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gpsgate.com/services/", ConfigurationName="ReportingReference.ReportingSoap")]
    public interface ReportingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReports", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.GetReportsResponse> GetReportsAsync(ReportingReference.GetReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GenerateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.GenerateReportResponse> GenerateReportAsync(ReportingReference.GenerateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/FetchReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.FetchReportResponse> FetchReportAsync(ReportingReference.FetchReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReportStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.GetReportStatusResponse> GetReportStatusAsync(ReportingReference.GetReportStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/CancelReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.CancelReportResponse> CancelReportAsync(ReportingReference.CancelReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetProcessingReports", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingReference.GetProcessingReportsResponse> GetProcessingReportsAsync(ReportingReference.GetProcessingReportsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReports", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetReportsRequestBody Body;
        
        public GetReportsRequest()
        {
        }
        
        public GetReportsRequest(ReportingReference.GetReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        public GetReportsRequestBody()
        {
        }
        
        public GetReportsRequestBody(string strSessionID, int iApplicationID)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportsResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetReportsResponseBody Body;
        
        public GetReportsResponse()
        {
        }
        
        public GetReportsResponse(ReportingReference.GetReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetReportsResult;
        
        public GetReportsResponseBody()
        {
        }
        
        public GetReportsResponseBody(System.Xml.XmlElement GetReportsResult)
        {
            this.GetReportsResult = GetReportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GenerateReportRequestBody Body;
        
        public GenerateReportRequest()
        {
        }
        
        public GenerateReportRequest(ReportingReference.GenerateReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GenerateReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iReportID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        public GenerateReportRequestBody()
        {
        }
        
        public GenerateReportRequestBody(string strSessionID, int iReportID, System.DateTime startDate, System.DateTime endDate)
        {
            this.strSessionID = strSessionID;
            this.iReportID = iReportID;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GenerateReportResponseBody Body;
        
        public GenerateReportResponse()
        {
        }
        
        public GenerateReportResponse(ReportingReference.GenerateReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GenerateReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GenerateReportResult;
        
        public GenerateReportResponseBody()
        {
        }
        
        public GenerateReportResponseBody(System.Xml.XmlElement GenerateReportResult)
        {
            this.GenerateReportResult = GenerateReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.FetchReportRequestBody Body;
        
        public FetchReportRequest()
        {
        }
        
        public FetchReportRequest(ReportingReference.FetchReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class FetchReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public FetchReportRequestBody()
        {
        }
        
        public FetchReportRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.FetchReportResponseBody Body;
        
        public FetchReportResponse()
        {
        }
        
        public FetchReportResponse(ReportingReference.FetchReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class FetchReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement FetchReportResult;
        
        public FetchReportResponseBody()
        {
        }
        
        public FetchReportResponseBody(System.Xml.XmlElement FetchReportResult)
        {
            this.FetchReportResult = FetchReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportStatus", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetReportStatusRequestBody Body;
        
        public GetReportStatusRequest()
        {
        }
        
        public GetReportStatusRequest(ReportingReference.GetReportStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public GetReportStatusRequestBody()
        {
        }
        
        public GetReportStatusRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportStatusResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetReportStatusResponseBody Body;
        
        public GetReportStatusResponse()
        {
        }
        
        public GetReportStatusResponse(ReportingReference.GetReportStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetReportStatusResult;
        
        public GetReportStatusResponseBody()
        {
        }
        
        public GetReportStatusResponseBody(System.Xml.XmlElement GetReportStatusResult)
        {
            this.GetReportStatusResult = GetReportStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.CancelReportRequestBody Body;
        
        public CancelReportRequest()
        {
        }
        
        public CancelReportRequest(ReportingReference.CancelReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class CancelReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public CancelReportRequestBody()
        {
        }
        
        public CancelReportRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.CancelReportResponseBody Body;
        
        public CancelReportResponse()
        {
        }
        
        public CancelReportResponse(ReportingReference.CancelReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class CancelReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement CancelReportResult;
        
        public CancelReportResponseBody()
        {
        }
        
        public CancelReportResponseBody(System.Xml.XmlElement CancelReportResult)
        {
            this.CancelReportResult = CancelReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessingReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessingReports", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetProcessingReportsRequestBody Body;
        
        public GetProcessingReportsRequest()
        {
        }
        
        public GetProcessingReportsRequest(ReportingReference.GetProcessingReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetProcessingReportsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iAppplicationID;
        
        public GetProcessingReportsRequestBody()
        {
        }
        
        public GetProcessingReportsRequestBody(string strSessionID, int iAppplicationID)
        {
            this.strSessionID = strSessionID;
            this.iAppplicationID = iAppplicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessingReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessingReportsResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingReference.GetProcessingReportsResponseBody Body;
        
        public GetProcessingReportsResponse()
        {
        }
        
        public GetProcessingReportsResponse(ReportingReference.GetProcessingReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetProcessingReportsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetProcessingReportsResult;
        
        public GetProcessingReportsResponseBody()
        {
        }
        
        public GetProcessingReportsResponseBody(System.Xml.XmlElement GetProcessingReportsResult)
        {
            this.GetProcessingReportsResult = GetProcessingReportsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ReportingSoapChannel : ReportingReference.ReportingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ReportingSoapClient : System.ServiceModel.ClientBase<ReportingReference.ReportingSoap>, ReportingReference.ReportingSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), ReportingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.GetReportsResponse> ReportingReference.ReportingSoap.GetReportsAsync(ReportingReference.GetReportsRequest request)
        {
            return base.Channel.GetReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.GetReportsResponse> GetReportsAsync(string strSessionID, int iApplicationID)
        {
            ReportingReference.GetReportsRequest inValue = new ReportingReference.GetReportsRequest();
            inValue.Body = new ReportingReference.GetReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            return ((ReportingReference.ReportingSoap)(this)).GetReportsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.GenerateReportResponse> ReportingReference.ReportingSoap.GenerateReportAsync(ReportingReference.GenerateReportRequest request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.GenerateReportResponse> GenerateReportAsync(string strSessionID, int iReportID, System.DateTime startDate, System.DateTime endDate)
        {
            ReportingReference.GenerateReportRequest inValue = new ReportingReference.GenerateReportRequest();
            inValue.Body = new ReportingReference.GenerateReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iReportID = iReportID;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((ReportingReference.ReportingSoap)(this)).GenerateReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.FetchReportResponse> ReportingReference.ReportingSoap.FetchReportAsync(ReportingReference.FetchReportRequest request)
        {
            return base.Channel.FetchReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.FetchReportResponse> FetchReportAsync(string strSessionID, int iHandleID)
        {
            ReportingReference.FetchReportRequest inValue = new ReportingReference.FetchReportRequest();
            inValue.Body = new ReportingReference.FetchReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingReference.ReportingSoap)(this)).FetchReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.GetReportStatusResponse> ReportingReference.ReportingSoap.GetReportStatusAsync(ReportingReference.GetReportStatusRequest request)
        {
            return base.Channel.GetReportStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.GetReportStatusResponse> GetReportStatusAsync(string strSessionID, int iHandleID)
        {
            ReportingReference.GetReportStatusRequest inValue = new ReportingReference.GetReportStatusRequest();
            inValue.Body = new ReportingReference.GetReportStatusRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingReference.ReportingSoap)(this)).GetReportStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.CancelReportResponse> ReportingReference.ReportingSoap.CancelReportAsync(ReportingReference.CancelReportRequest request)
        {
            return base.Channel.CancelReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.CancelReportResponse> CancelReportAsync(string strSessionID, int iHandleID)
        {
            ReportingReference.CancelReportRequest inValue = new ReportingReference.CancelReportRequest();
            inValue.Body = new ReportingReference.CancelReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingReference.ReportingSoap)(this)).CancelReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingReference.GetProcessingReportsResponse> ReportingReference.ReportingSoap.GetProcessingReportsAsync(ReportingReference.GetProcessingReportsRequest request)
        {
            return base.Channel.GetProcessingReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingReference.GetProcessingReportsResponse> GetProcessingReportsAsync(string strSessionID, int iAppplicationID)
        {
            ReportingReference.GetProcessingReportsRequest inValue = new ReportingReference.GetProcessingReportsRequest();
            inValue.Body = new ReportingReference.GetProcessingReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iAppplicationID = iAppplicationID;
            return ((ReportingReference.ReportingSoap)(this)).GetProcessingReportsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/Reporting.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/Reporting.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ReportingSoap,
            
            ReportingSoap12,
        }
    }
}
