//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://gpsgate.com/services/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gpsgate.com/services/", ConfigurationName="TrackReference1.TracksSoap")]
    public interface TracksSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetTracksByUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.GetTracksByUsersResponse> GetTracksByUsersAsync(TrackReference1.GetTracksByUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetTripsByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.GetTripsByUserResponse> GetTripsByUserAsync(TrackReference1.GetTripsByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetTrackDataChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.GetTrackDataChunkResponse> GetTrackDataChunkAsync(TrackReference1.GetTrackDataChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetFatPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.GetFatPointsResponse> GetFatPointsAsync(TrackReference1.GetFatPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetLifeRecorderByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.GetLifeRecorderByUserResponse> GetLifeRecorderByUserAsync(TrackReference1.GetLifeRecorderByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/SetLifeTrackRecorderFilters", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.SetLifeTrackRecorderFiltersResponse> SetLifeTrackRecorderFiltersAsync(TrackReference1.SetLifeTrackRecorderFiltersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/DeleteTrack", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackReference1.DeleteTrackResponse> DeleteTrackAsync(TrackReference1.DeleteTrackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTracksByUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTracksByUsers", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTracksByUsersRequestBody Body;
        
        public GetTracksByUsersRequest()
        {
        }
        
        public GetTracksByUsersRequest(TrackReference1.GetTracksByUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTracksByUsersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TrackReference1.ArrayOfInt arrUserIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dtEnd;
        
        public GetTracksByUsersRequestBody()
        {
        }
        
        public GetTracksByUsersRequestBody(string strSessionID, int iApplicationID, TrackReference1.ArrayOfInt arrUserIDs, System.DateTime dtStart, System.DateTime dtEnd)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.arrUserIDs = arrUserIDs;
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTracksByUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTracksByUsersResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTracksByUsersResponseBody Body;
        
        public GetTracksByUsersResponse()
        {
        }
        
        public GetTracksByUsersResponse(TrackReference1.GetTracksByUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTracksByUsersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetTracksByUsersResult;
        
        public GetTracksByUsersResponseBody()
        {
        }
        
        public GetTracksByUsersResponseBody(System.Xml.Linq.XElement GetTracksByUsersResult)
        {
            this.GetTracksByUsersResult = GetTracksByUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripsByUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTripsByUser", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTripsByUserRequestBody Body;
        
        public GetTripsByUserRequest()
        {
        }
        
        public GetTripsByUserRequest(TrackReference1.GetTripsByUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTripsByUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dtEnd;
        
        public GetTripsByUserRequestBody()
        {
        }
        
        public GetTripsByUserRequestBody(string strSessionID, int iApplicationID, int iUserID, System.DateTime dtStart, System.DateTime dtEnd)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iUserID = iUserID;
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTripsByUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTripsByUserResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTripsByUserResponseBody Body;
        
        public GetTripsByUserResponse()
        {
        }
        
        public GetTripsByUserResponse(TrackReference1.GetTripsByUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTripsByUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetTripsByUserResult;
        
        public GetTripsByUserResponseBody()
        {
        }
        
        public GetTripsByUserResponseBody(System.Xml.Linq.XElement GetTripsByUserResult)
        {
            this.GetTripsByUserResult = GetTripsByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrackDataChunkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrackDataChunk", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTrackDataChunkRequestBody Body;
        
        public GetTrackDataChunkRequest()
        {
        }
        
        public GetTrackDataChunkRequest(TrackReference1.GetTrackDataChunkRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTrackDataChunkRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iTrackInfoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dtEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int iStartIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int iStopIndex;
        
        public GetTrackDataChunkRequestBody()
        {
        }
        
        public GetTrackDataChunkRequestBody(string strSessionID, int iApplicationID, int iTrackInfoID, System.DateTime dtStart, System.DateTime dtEnd, int iStartIndex, int iStopIndex)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iTrackInfoID = iTrackInfoID;
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
            this.iStartIndex = iStartIndex;
            this.iStopIndex = iStopIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrackDataChunkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrackDataChunkResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetTrackDataChunkResponseBody Body;
        
        public GetTrackDataChunkResponse()
        {
        }
        
        public GetTrackDataChunkResponse(TrackReference1.GetTrackDataChunkResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetTrackDataChunkResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetTrackDataChunkResult;
        
        public GetTrackDataChunkResponseBody()
        {
        }
        
        public GetTrackDataChunkResponseBody(System.Xml.Linq.XElement GetTrackDataChunkResult)
        {
            this.GetTrackDataChunkResult = GetTrackDataChunkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFatPointsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFatPoints", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetFatPointsRequestBody Body;
        
        public GetFatPointsRequest()
        {
        }
        
        public GetFatPointsRequest(TrackReference1.GetFatPointsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetFatPointsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iTrackInfoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dtStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dtEnd;
        
        public GetFatPointsRequestBody()
        {
        }
        
        public GetFatPointsRequestBody(string strSessionID, int iApplicationID, int iTrackInfoID, System.DateTime dtStart, System.DateTime dtEnd)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iTrackInfoID = iTrackInfoID;
            this.dtStart = dtStart;
            this.dtEnd = dtEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFatPointsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFatPointsResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetFatPointsResponseBody Body;
        
        public GetFatPointsResponse()
        {
        }
        
        public GetFatPointsResponse(TrackReference1.GetFatPointsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetFatPointsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFatPointsResult;
        
        public GetFatPointsResponseBody()
        {
        }
        
        public GetFatPointsResponseBody(System.Xml.Linq.XElement GetFatPointsResult)
        {
            this.GetFatPointsResult = GetFatPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLifeRecorderByUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLifeRecorderByUser", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetLifeRecorderByUserRequestBody Body;
        
        public GetLifeRecorderByUserRequest()
        {
        }
        
        public GetLifeRecorderByUserRequest(TrackReference1.GetLifeRecorderByUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetLifeRecorderByUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iOwnerID;
        
        public GetLifeRecorderByUserRequestBody()
        {
        }
        
        public GetLifeRecorderByUserRequestBody(string strSessionID, int iApplicationID, int iOwnerID)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iOwnerID = iOwnerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLifeRecorderByUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLifeRecorderByUserResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.GetLifeRecorderByUserResponseBody Body;
        
        public GetLifeRecorderByUserResponse()
        {
        }
        
        public GetLifeRecorderByUserResponse(TrackReference1.GetLifeRecorderByUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetLifeRecorderByUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetLifeRecorderByUserResult;
        
        public GetLifeRecorderByUserResponseBody()
        {
        }
        
        public GetLifeRecorderByUserResponseBody(System.Xml.Linq.XElement GetLifeRecorderByUserResult)
        {
            this.GetLifeRecorderByUserResult = GetLifeRecorderByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetLifeTrackRecorderFiltersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetLifeTrackRecorderFilters", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.SetLifeTrackRecorderFiltersRequestBody Body;
        
        public SetLifeTrackRecorderFiltersRequest()
        {
        }
        
        public SetLifeTrackRecorderFiltersRequest(TrackReference1.SetLifeTrackRecorderFiltersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class SetLifeTrackRecorderFiltersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iOwnerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double dblTimeFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double dblDistanceFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double dblRestartInterval;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double dblRestartIntervalOffset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double dblDirectionFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double dblDirectionThreshold;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double dblSpeedFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double dblRestartTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public double dblRestartDistance;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double dblSmsTimeFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool bMotion;
        
        public SetLifeTrackRecorderFiltersRequestBody()
        {
        }
        
        public SetLifeTrackRecorderFiltersRequestBody(string strSessionID, int iApplicationID, int iOwnerID, double dblTimeFilter, double dblDistanceFilter, double dblRestartInterval, double dblRestartIntervalOffset, double dblDirectionFilter, double dblDirectionThreshold, double dblSpeedFilter, double dblRestartTime, double dblRestartDistance, double dblSmsTimeFilter, bool bMotion)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iOwnerID = iOwnerID;
            this.dblTimeFilter = dblTimeFilter;
            this.dblDistanceFilter = dblDistanceFilter;
            this.dblRestartInterval = dblRestartInterval;
            this.dblRestartIntervalOffset = dblRestartIntervalOffset;
            this.dblDirectionFilter = dblDirectionFilter;
            this.dblDirectionThreshold = dblDirectionThreshold;
            this.dblSpeedFilter = dblSpeedFilter;
            this.dblRestartTime = dblRestartTime;
            this.dblRestartDistance = dblRestartDistance;
            this.dblSmsTimeFilter = dblSmsTimeFilter;
            this.bMotion = bMotion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetLifeTrackRecorderFiltersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetLifeTrackRecorderFiltersResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.SetLifeTrackRecorderFiltersResponseBody Body;
        
        public SetLifeTrackRecorderFiltersResponse()
        {
        }
        
        public SetLifeTrackRecorderFiltersResponse(TrackReference1.SetLifeTrackRecorderFiltersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class SetLifeTrackRecorderFiltersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SetLifeTrackRecorderFiltersResult;
        
        public SetLifeTrackRecorderFiltersResponseBody()
        {
        }
        
        public SetLifeTrackRecorderFiltersResponseBody(System.Xml.Linq.XElement SetLifeTrackRecorderFiltersResult)
        {
            this.SetLifeTrackRecorderFiltersResult = SetLifeTrackRecorderFiltersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTrackRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTrack", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.DeleteTrackRequestBody Body;
        
        public DeleteTrackRequest()
        {
        }
        
        public DeleteTrackRequest(TrackReference1.DeleteTrackRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class DeleteTrackRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iTrackInfoID;
        
        public DeleteTrackRequestBody()
        {
        }
        
        public DeleteTrackRequestBody(string strSessionID, int iApplicationID, int iTrackInfoID)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
            this.iTrackInfoID = iTrackInfoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTrackResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTrackResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public TrackReference1.DeleteTrackResponseBody Body;
        
        public DeleteTrackResponse()
        {
        }
        
        public DeleteTrackResponse(TrackReference1.DeleteTrackResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class DeleteTrackResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteTrackResult;
        
        public DeleteTrackResponseBody()
        {
        }
        
        public DeleteTrackResponseBody(System.Xml.Linq.XElement DeleteTrackResult)
        {
            this.DeleteTrackResult = DeleteTrackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface TracksSoapChannel : TrackReference1.TracksSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TracksSoapClient : System.ServiceModel.ClientBase<TrackReference1.TracksSoap>, TrackReference1.TracksSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TracksSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TracksSoapClient.GetBindingForEndpoint(endpointConfiguration), TracksSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracksSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TracksSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracksSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TracksSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.GetTracksByUsersResponse> TrackReference1.TracksSoap.GetTracksByUsersAsync(TrackReference1.GetTracksByUsersRequest request)
        {
            return base.Channel.GetTracksByUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.GetTracksByUsersResponse> GetTracksByUsersAsync(string strSessionID, int iApplicationID, TrackReference1.ArrayOfInt arrUserIDs, System.DateTime dtStart, System.DateTime dtEnd)
        {
            TrackReference1.GetTracksByUsersRequest inValue = new TrackReference1.GetTracksByUsersRequest();
            inValue.Body = new TrackReference1.GetTracksByUsersRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.arrUserIDs = arrUserIDs;
            inValue.Body.dtStart = dtStart;
            inValue.Body.dtEnd = dtEnd;
            return ((TrackReference1.TracksSoap)(this)).GetTracksByUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.GetTripsByUserResponse> TrackReference1.TracksSoap.GetTripsByUserAsync(TrackReference1.GetTripsByUserRequest request)
        {
            return base.Channel.GetTripsByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.GetTripsByUserResponse> GetTripsByUserAsync(string strSessionID, int iApplicationID, int iUserID, System.DateTime dtStart, System.DateTime dtEnd)
        {
            TrackReference1.GetTripsByUserRequest inValue = new TrackReference1.GetTripsByUserRequest();
            inValue.Body = new TrackReference1.GetTripsByUserRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iUserID = iUserID;
            inValue.Body.dtStart = dtStart;
            inValue.Body.dtEnd = dtEnd;
            return ((TrackReference1.TracksSoap)(this)).GetTripsByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.GetTrackDataChunkResponse> TrackReference1.TracksSoap.GetTrackDataChunkAsync(TrackReference1.GetTrackDataChunkRequest request)
        {
            return base.Channel.GetTrackDataChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.GetTrackDataChunkResponse> GetTrackDataChunkAsync(string strSessionID, int iApplicationID, int iTrackInfoID, System.DateTime dtStart, System.DateTime dtEnd, int iStartIndex, int iStopIndex)
        {
            TrackReference1.GetTrackDataChunkRequest inValue = new TrackReference1.GetTrackDataChunkRequest();
            inValue.Body = new TrackReference1.GetTrackDataChunkRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iTrackInfoID = iTrackInfoID;
            inValue.Body.dtStart = dtStart;
            inValue.Body.dtEnd = dtEnd;
            inValue.Body.iStartIndex = iStartIndex;
            inValue.Body.iStopIndex = iStopIndex;
            return ((TrackReference1.TracksSoap)(this)).GetTrackDataChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.GetFatPointsResponse> TrackReference1.TracksSoap.GetFatPointsAsync(TrackReference1.GetFatPointsRequest request)
        {
            return base.Channel.GetFatPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.GetFatPointsResponse> GetFatPointsAsync(string strSessionID, int iApplicationID, int iTrackInfoID, System.DateTime dtStart, System.DateTime dtEnd)
        {
            TrackReference1.GetFatPointsRequest inValue = new TrackReference1.GetFatPointsRequest();
            inValue.Body = new TrackReference1.GetFatPointsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iTrackInfoID = iTrackInfoID;
            inValue.Body.dtStart = dtStart;
            inValue.Body.dtEnd = dtEnd;
            return ((TrackReference1.TracksSoap)(this)).GetFatPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.GetLifeRecorderByUserResponse> TrackReference1.TracksSoap.GetLifeRecorderByUserAsync(TrackReference1.GetLifeRecorderByUserRequest request)
        {
            return base.Channel.GetLifeRecorderByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.GetLifeRecorderByUserResponse> GetLifeRecorderByUserAsync(string strSessionID, int iApplicationID, int iOwnerID)
        {
            TrackReference1.GetLifeRecorderByUserRequest inValue = new TrackReference1.GetLifeRecorderByUserRequest();
            inValue.Body = new TrackReference1.GetLifeRecorderByUserRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iOwnerID = iOwnerID;
            return ((TrackReference1.TracksSoap)(this)).GetLifeRecorderByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.SetLifeTrackRecorderFiltersResponse> TrackReference1.TracksSoap.SetLifeTrackRecorderFiltersAsync(TrackReference1.SetLifeTrackRecorderFiltersRequest request)
        {
            return base.Channel.SetLifeTrackRecorderFiltersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.SetLifeTrackRecorderFiltersResponse> SetLifeTrackRecorderFiltersAsync(string strSessionID, int iApplicationID, int iOwnerID, double dblTimeFilter, double dblDistanceFilter, double dblRestartInterval, double dblRestartIntervalOffset, double dblDirectionFilter, double dblDirectionThreshold, double dblSpeedFilter, double dblRestartTime, double dblRestartDistance, double dblSmsTimeFilter, bool bMotion)
        {
            TrackReference1.SetLifeTrackRecorderFiltersRequest inValue = new TrackReference1.SetLifeTrackRecorderFiltersRequest();
            inValue.Body = new TrackReference1.SetLifeTrackRecorderFiltersRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iOwnerID = iOwnerID;
            inValue.Body.dblTimeFilter = dblTimeFilter;
            inValue.Body.dblDistanceFilter = dblDistanceFilter;
            inValue.Body.dblRestartInterval = dblRestartInterval;
            inValue.Body.dblRestartIntervalOffset = dblRestartIntervalOffset;
            inValue.Body.dblDirectionFilter = dblDirectionFilter;
            inValue.Body.dblDirectionThreshold = dblDirectionThreshold;
            inValue.Body.dblSpeedFilter = dblSpeedFilter;
            inValue.Body.dblRestartTime = dblRestartTime;
            inValue.Body.dblRestartDistance = dblRestartDistance;
            inValue.Body.dblSmsTimeFilter = dblSmsTimeFilter;
            inValue.Body.bMotion = bMotion;
            return ((TrackReference1.TracksSoap)(this)).SetLifeTrackRecorderFiltersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackReference1.DeleteTrackResponse> TrackReference1.TracksSoap.DeleteTrackAsync(TrackReference1.DeleteTrackRequest request)
        {
            return base.Channel.DeleteTrackAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackReference1.DeleteTrackResponse> DeleteTrackAsync(string strSessionID, int iApplicationID, int iTrackInfoID)
        {
            TrackReference1.DeleteTrackRequest inValue = new TrackReference1.DeleteTrackRequest();
            inValue.Body = new TrackReference1.DeleteTrackRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            inValue.Body.iTrackInfoID = iTrackInfoID;
            return ((TrackReference1.TracksSoap)(this)).DeleteTrackAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TracksSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TracksSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TracksSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/tracks.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TracksSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/tracks.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TracksSoap,
            
            TracksSoap12,
        }
    }
}
