//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gpsgate.com/services/", ConfigurationName="ReportingServiceReference1.ReportingSoap")]
    public interface ReportingSoap
    {
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReports", ReplyAction="*")]
        ReportingServiceReference1.GetReportsResponse GetReports(ReportingServiceReference1.GetReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReports", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetReportsResponse> GetReportsAsync(ReportingServiceReference1.GetReportsRequest request);
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GenerateReport", ReplyAction="*")]
        ReportingServiceReference1.GenerateReportResponse GenerateReport(ReportingServiceReference1.GenerateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GenerateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.GenerateReportResponse> GenerateReportAsync(ReportingServiceReference1.GenerateReportRequest request);
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/FetchReport", ReplyAction="*")]
        ReportingServiceReference1.FetchReportResponse FetchReport(ReportingServiceReference1.FetchReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/FetchReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.FetchReportResponse> FetchReportAsync(ReportingServiceReference1.FetchReportRequest request);
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReportStatus", ReplyAction="*")]
        ReportingServiceReference1.GetReportStatusResponse GetReportStatus(ReportingServiceReference1.GetReportStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetReportStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetReportStatusResponse> GetReportStatusAsync(ReportingServiceReference1.GetReportStatusRequest request);
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/CancelReport", ReplyAction="*")]
        ReportingServiceReference1.CancelReportResponse CancelReport(ReportingServiceReference1.CancelReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/CancelReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.CancelReportResponse> CancelReportAsync(ReportingServiceReference1.CancelReportRequest request);
        
        // CODEGEN: Generating message contract since element name strSessionID from namespace http://gpsgate.com/services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetProcessingReports", ReplyAction="*")]
        ReportingServiceReference1.GetProcessingReportsResponse GetProcessingReports(ReportingServiceReference1.GetProcessingReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gpsgate.com/services/GetProcessingReports", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetProcessingReportsResponse> GetProcessingReportsAsync(ReportingServiceReference1.GetProcessingReportsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReports", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetReportsRequestBody Body;
        
        public GetReportsRequest()
        {
        }
        
        public GetReportsRequest(ReportingServiceReference1.GetReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iApplicationID;
        
        public GetReportsRequestBody()
        {
        }
        
        public GetReportsRequestBody(string strSessionID, int iApplicationID)
        {
            this.strSessionID = strSessionID;
            this.iApplicationID = iApplicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportsResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetReportsResponseBody Body;
        
        public GetReportsResponse()
        {
        }
        
        public GetReportsResponse(ReportingServiceReference1.GetReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetReportsResult;
        
        public GetReportsResponseBody()
        {
        }
        
        public GetReportsResponseBody(System.Xml.XmlElement GetReportsResult)
        {
            this.GetReportsResult = GetReportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GenerateReportRequestBody Body;
        
        public GenerateReportRequest()
        {
        }
        
        public GenerateReportRequest(ReportingServiceReference1.GenerateReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GenerateReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iReportID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        public GenerateReportRequestBody()
        {
        }
        
        public GenerateReportRequestBody(string strSessionID, int iReportID, System.DateTime startDate, System.DateTime endDate)
        {
            this.strSessionID = strSessionID;
            this.iReportID = iReportID;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GenerateReportResponseBody Body;
        
        public GenerateReportResponse()
        {
        }
        
        public GenerateReportResponse(ReportingServiceReference1.GenerateReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GenerateReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GenerateReportResult;
        
        public GenerateReportResponseBody()
        {
        }
        
        public GenerateReportResponseBody(System.Xml.XmlElement GenerateReportResult)
        {
            this.GenerateReportResult = GenerateReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.FetchReportRequestBody Body;
        
        public FetchReportRequest()
        {
        }
        
        public FetchReportRequest(ReportingServiceReference1.FetchReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class FetchReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public FetchReportRequestBody()
        {
        }
        
        public FetchReportRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.FetchReportResponseBody Body;
        
        public FetchReportResponse()
        {
        }
        
        public FetchReportResponse(ReportingServiceReference1.FetchReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class FetchReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement FetchReportResult;
        
        public FetchReportResponseBody()
        {
        }
        
        public FetchReportResponseBody(System.Xml.XmlElement FetchReportResult)
        {
            this.FetchReportResult = FetchReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportStatus", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetReportStatusRequestBody Body;
        
        public GetReportStatusRequest()
        {
        }
        
        public GetReportStatusRequest(ReportingServiceReference1.GetReportStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public GetReportStatusRequestBody()
        {
        }
        
        public GetReportStatusRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportStatusResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetReportStatusResponseBody Body;
        
        public GetReportStatusResponse()
        {
        }
        
        public GetReportStatusResponse(ReportingServiceReference1.GetReportStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetReportStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetReportStatusResult;
        
        public GetReportStatusResponseBody()
        {
        }
        
        public GetReportStatusResponseBody(System.Xml.XmlElement GetReportStatusResult)
        {
            this.GetReportStatusResult = GetReportStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReport", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.CancelReportRequestBody Body;
        
        public CancelReportRequest()
        {
        }
        
        public CancelReportRequest(ReportingServiceReference1.CancelReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class CancelReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iHandleID;
        
        public CancelReportRequestBody()
        {
        }
        
        public CancelReportRequestBody(string strSessionID, int iHandleID)
        {
            this.strSessionID = strSessionID;
            this.iHandleID = iHandleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReportResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.CancelReportResponseBody Body;
        
        public CancelReportResponse()
        {
        }
        
        public CancelReportResponse(ReportingServiceReference1.CancelReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class CancelReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement CancelReportResult;
        
        public CancelReportResponseBody()
        {
        }
        
        public CancelReportResponseBody(System.Xml.XmlElement CancelReportResult)
        {
            this.CancelReportResult = CancelReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessingReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessingReports", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetProcessingReportsRequestBody Body;
        
        public GetProcessingReportsRequest()
        {
        }
        
        public GetProcessingReportsRequest(ReportingServiceReference1.GetProcessingReportsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetProcessingReportsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iAppplicationID;
        
        public GetProcessingReportsRequestBody()
        {
        }
        
        public GetProcessingReportsRequestBody(string strSessionID, int iAppplicationID)
        {
            this.strSessionID = strSessionID;
            this.iAppplicationID = iAppplicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessingReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessingReportsResponse", Namespace="http://gpsgate.com/services/", Order=0)]
        public ReportingServiceReference1.GetProcessingReportsResponseBody Body;
        
        public GetProcessingReportsResponse()
        {
        }
        
        public GetProcessingReportsResponse(ReportingServiceReference1.GetProcessingReportsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpsgate.com/services/")]
    public partial class GetProcessingReportsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetProcessingReportsResult;
        
        public GetProcessingReportsResponseBody()
        {
        }
        
        public GetProcessingReportsResponseBody(System.Xml.XmlElement GetProcessingReportsResult)
        {
            this.GetProcessingReportsResult = GetProcessingReportsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ReportingSoapChannel : ReportingServiceReference1.ReportingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ReportingSoapClient : System.ServiceModel.ClientBase<ReportingServiceReference1.ReportingSoap>, ReportingServiceReference1.ReportingSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), ReportingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.GetReportsResponse ReportingServiceReference1.ReportingSoap.GetReports(ReportingServiceReference1.GetReportsRequest request)
        {
            return base.Channel.GetReports(request);
        }
        
        public System.Xml.XmlElement GetReports(string strSessionID, int iApplicationID)
        {
            ReportingServiceReference1.GetReportsRequest inValue = new ReportingServiceReference1.GetReportsRequest();
            inValue.Body = new ReportingServiceReference1.GetReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            ReportingServiceReference1.GetReportsResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).GetReports(inValue);
            return retVal.Body.GetReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetReportsResponse> ReportingServiceReference1.ReportingSoap.GetReportsAsync(ReportingServiceReference1.GetReportsRequest request)
        {
            return base.Channel.GetReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.GetReportsResponse> GetReportsAsync(string strSessionID, int iApplicationID)
        {
            ReportingServiceReference1.GetReportsRequest inValue = new ReportingServiceReference1.GetReportsRequest();
            inValue.Body = new ReportingServiceReference1.GetReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iApplicationID = iApplicationID;
            return ((ReportingServiceReference1.ReportingSoap)(this)).GetReportsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.GenerateReportResponse ReportingServiceReference1.ReportingSoap.GenerateReport(ReportingServiceReference1.GenerateReportRequest request)
        {
            return base.Channel.GenerateReport(request);
        }
        
        public System.Xml.XmlElement GenerateReport(string strSessionID, int iReportID, System.DateTime startDate, System.DateTime endDate)
        {
            ReportingServiceReference1.GenerateReportRequest inValue = new ReportingServiceReference1.GenerateReportRequest();
            inValue.Body = new ReportingServiceReference1.GenerateReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iReportID = iReportID;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            ReportingServiceReference1.GenerateReportResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).GenerateReport(inValue);
            return retVal.Body.GenerateReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.GenerateReportResponse> ReportingServiceReference1.ReportingSoap.GenerateReportAsync(ReportingServiceReference1.GenerateReportRequest request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.GenerateReportResponse> GenerateReportAsync(string strSessionID, int iReportID, System.DateTime startDate, System.DateTime endDate)
        {
            ReportingServiceReference1.GenerateReportRequest inValue = new ReportingServiceReference1.GenerateReportRequest();
            inValue.Body = new ReportingServiceReference1.GenerateReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iReportID = iReportID;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((ReportingServiceReference1.ReportingSoap)(this)).GenerateReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.FetchReportResponse ReportingServiceReference1.ReportingSoap.FetchReport(ReportingServiceReference1.FetchReportRequest request)
        {
            return base.Channel.FetchReport(request);
        }
        
        public System.Xml.XmlElement FetchReport(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.FetchReportRequest inValue = new ReportingServiceReference1.FetchReportRequest();
            inValue.Body = new ReportingServiceReference1.FetchReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            ReportingServiceReference1.FetchReportResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).FetchReport(inValue);
            return retVal.Body.FetchReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.FetchReportResponse> ReportingServiceReference1.ReportingSoap.FetchReportAsync(ReportingServiceReference1.FetchReportRequest request)
        {
            return base.Channel.FetchReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.FetchReportResponse> FetchReportAsync(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.FetchReportRequest inValue = new ReportingServiceReference1.FetchReportRequest();
            inValue.Body = new ReportingServiceReference1.FetchReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingServiceReference1.ReportingSoap)(this)).FetchReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.GetReportStatusResponse ReportingServiceReference1.ReportingSoap.GetReportStatus(ReportingServiceReference1.GetReportStatusRequest request)
        {
            return base.Channel.GetReportStatus(request);
        }
        
        public System.Xml.XmlElement GetReportStatus(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.GetReportStatusRequest inValue = new ReportingServiceReference1.GetReportStatusRequest();
            inValue.Body = new ReportingServiceReference1.GetReportStatusRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            ReportingServiceReference1.GetReportStatusResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).GetReportStatus(inValue);
            return retVal.Body.GetReportStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetReportStatusResponse> ReportingServiceReference1.ReportingSoap.GetReportStatusAsync(ReportingServiceReference1.GetReportStatusRequest request)
        {
            return base.Channel.GetReportStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.GetReportStatusResponse> GetReportStatusAsync(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.GetReportStatusRequest inValue = new ReportingServiceReference1.GetReportStatusRequest();
            inValue.Body = new ReportingServiceReference1.GetReportStatusRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingServiceReference1.ReportingSoap)(this)).GetReportStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.CancelReportResponse ReportingServiceReference1.ReportingSoap.CancelReport(ReportingServiceReference1.CancelReportRequest request)
        {
            return base.Channel.CancelReport(request);
        }
        
        public System.Xml.XmlElement CancelReport(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.CancelReportRequest inValue = new ReportingServiceReference1.CancelReportRequest();
            inValue.Body = new ReportingServiceReference1.CancelReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            ReportingServiceReference1.CancelReportResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).CancelReport(inValue);
            return retVal.Body.CancelReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.CancelReportResponse> ReportingServiceReference1.ReportingSoap.CancelReportAsync(ReportingServiceReference1.CancelReportRequest request)
        {
            return base.Channel.CancelReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.CancelReportResponse> CancelReportAsync(string strSessionID, int iHandleID)
        {
            ReportingServiceReference1.CancelReportRequest inValue = new ReportingServiceReference1.CancelReportRequest();
            inValue.Body = new ReportingServiceReference1.CancelReportRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iHandleID = iHandleID;
            return ((ReportingServiceReference1.ReportingSoap)(this)).CancelReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportingServiceReference1.GetProcessingReportsResponse ReportingServiceReference1.ReportingSoap.GetProcessingReports(ReportingServiceReference1.GetProcessingReportsRequest request)
        {
            return base.Channel.GetProcessingReports(request);
        }
        
        public System.Xml.XmlElement GetProcessingReports(string strSessionID, int iAppplicationID)
        {
            ReportingServiceReference1.GetProcessingReportsRequest inValue = new ReportingServiceReference1.GetProcessingReportsRequest();
            inValue.Body = new ReportingServiceReference1.GetProcessingReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iAppplicationID = iAppplicationID;
            ReportingServiceReference1.GetProcessingReportsResponse retVal = ((ReportingServiceReference1.ReportingSoap)(this)).GetProcessingReports(inValue);
            return retVal.Body.GetProcessingReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportingServiceReference1.GetProcessingReportsResponse> ReportingServiceReference1.ReportingSoap.GetProcessingReportsAsync(ReportingServiceReference1.GetProcessingReportsRequest request)
        {
            return base.Channel.GetProcessingReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportingServiceReference1.GetProcessingReportsResponse> GetProcessingReportsAsync(string strSessionID, int iAppplicationID)
        {
            ReportingServiceReference1.GetProcessingReportsRequest inValue = new ReportingServiceReference1.GetProcessingReportsRequest();
            inValue.Body = new ReportingServiceReference1.GetProcessingReportsRequestBody();
            inValue.Body.strSessionID = strSessionID;
            inValue.Body.iAppplicationID = iAppplicationID;
            return ((ReportingServiceReference1.ReportingSoap)(this)).GetProcessingReportsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/Reporting.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ReportingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://52.43.97.199/GpsGateServer/Services/Reporting.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ReportingSoap,
            
            ReportingSoap12,
        }
    }
}
